---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: application-gzip
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          portNumber: 8080
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.compressor
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
            response_direction_config:
              common_config:
                content_type:
                  - application/json
            compressor_library:
              name: for_response
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                memory_level: 3
                window_bits: 10
                compression_level: BEST_COMPRESSION
                compression_strategy: DEFAULT_STRATEGY
            remove_accept_encoding_header: true
---
# apiVersion: networking.istio.io/v1alpha3
# kind: EnvoyFilter
# metadata:
#   name: application-zstd
# spec:
#   configPatches:
#     - applyTo: HTTP_FILTER
#       match:
#         context: SIDECAR_OUTBOUND
#         listener:
#           portNumber: 8080
#           filterChain:
#             filter:
#               name: envoy.filters.network.http_connection_manager
#               subFilter:
#                 name: envoy.filters.http.router
#       patch:
#         operation: INSERT_BEFORE
#         value:
#           name: envoy.filters.http.compressor
#           typed_config:
#             '@type': type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
#             request_direction_config:
#               common_config:
#                 enabled:
#                   default_value: false
#                   runtime_key: request_compressor_enabled
#             response_direction_config:
#               common_config:
#                 content_type:
#                   - application/json
#             compressor_library:
#               name: for_response
#               typed_config:
#                 "@type": type.googleapis.com/envoy.extensions.compression.zstd.compressor.v3.Zstd
#             remove_accept_encoding_header: true
